sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - docker login -u oupisey -p @Gmail.com123 docker.io

deploy:
  provider: script
  skip_cleanup: true
  script: docker push mannydesigns/node
  on:
    branch: master

