sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - sudo docker login -u oupisey -p @Gmail.com123
  - sudo docker tag mannydesigns/node oupisey/node

deploy:
  provider: script
  script: sudo docker push oupisey/node
  on:
    branch: master

